name: Docker-Image CI

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Run buildx
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --output "type=image,push=false" \
          --tag stoxygen/tftpd-hpa:latest \
          --file Dockerfile .
  build-armhf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Run buildx
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --output "type=image,push=false" \
          --tag stoxygen/tftpd-hpa:latest \
          --file Dockerfile .
