name: Docker-Image CI

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: stoxygen/tftpd-hpa:latest
        platforms: linux/amd64
      
  build-armhf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: stoxygen/tftpd-hpa:latest
        platforms: linux/arm/v7
